In [41]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [46]:
from sklearn.datasets import load_iris
iris =load_iris()

In [47]:
from sklearn.model_selection import cross_val_score

# Logistic Regression score 

In [51]:
score_lg=cross_val_score(LogisticRegression(),iris.data,iris.target)
score_lg

/home/krishna/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [52]:
np.average(score_lg)

0.9733333333333334

# for Decision Tree 

In [53]:
score_D=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
score_D

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [54]:
np.average(score_D)

0.9600000000000002

# for svm score 

In [56]:
score_sm= cross_val_score(SVC(),iris.data,iris.target)

In [57]:
score_sm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [58]:
np.average(score_sm)

0.9666666666666666

# for Random Forest classifier 

In [59]:
score_RD=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
score_RD

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [61]:
np.average(score_RD)

0.96